### ISSUE TITLE
Building Broken when using -Dsite.exec_ee_log_level=TRACE

### ISSUE THREAD

**Issue by mikelj** [apavlo/h-store#190]
There are some pretty big errors when compiling with VOLT_TRACE() active. 

Truncated compile errors below:
https://gist.github.com/mikelj/e9e00e3f040ca9dd32e9

**Comment by malin1993ml** [comment]
I guess that's because some later commits changed the code of the indexes
and then it's not consistent with former VOLT_TRACE.

Comment out those three lines with TRACE information will do:
https://github.com/mikelj/h-store/blob/master/src/ee/indexes/tableindex.cpp#L74
https://github.com/mikelj/h-store/blob/master/src/ee/indexes/tableindex.cpp#L79
https://github.com/mikelj/h-store/blob/master/src/ee/indexes/allocatortracker.h#L78

BTW, this function (
https://github.com/mikelj/h-store/blob/master/src/ee/indexes/allocatortracker.h#L78)
in fact is already deleted in the main branch of H-Store as a bug fix
lately. I recommend fetching a new version of H-Store to avoid wrong stats
of memory consumption.

**Comment by mikelj** [comment]
Your latest commit fixed it for me when merged.

Thanks
